name: general_feature_flags_firebase
description: Firebase Remote Config adapter for general_feature_flags.
version: 0.1.1
homepage: https://rivendev.app
repository: https://github.com/rivendev-app/general_feature_flags
directory: general_feature_flags_firebase
# publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  general_feature_flags: ^0.1.1
  firebase_remote_config: ^6.1.4
  firebase_core: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  very_good_analysis: ^5.1.0

topics:
  - feature-flags
  - firebase
  - remote-config
  - flutter
