name: general_feature_flags_redis
description: Redis adapter for general_feature_flags (via HTTP/REST).
version: 0.1.0
homepage: https://rivendev.app
repository: https://github.com/rivendev-app/general_feature_flags
directory: general_feature_flags_redis
# publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  general_feature_flags: ^0.1.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  very_good_analysis: ^5.1.0

topics:
  - feature-flags
  - redis
  - remote-config
  - flutter
