name: general_feature_flags
description: A robust, multi-provider feature flag system for Flutter. Professional, extensible, and corporate-ready.
version: 0.1.1
homepage: https://rivendev.app
repository: https://github.com/rivendev-app/general_feature_flags
directory: general_feature_flags
issue_tracker: https://github.com/rivendev-app/general_feature_flags/issues
# publish_to: none # Removed for publication

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0
  crypto: ^3.0.3
  meta: ^1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  very_good_analysis: ^5.1.0
  mocktail: ^1.0.3

topics:
  - feature-flags
  - remote-config
  - flutter
  - ab-testing

flutter:
  uses-material-design: true
